### ISSUE TITLE
Latest SDK

### ISSUE THREAD

**Issue by realsurfer** [dasmurphy/testflight-module#3]
Hi,
Thanks for a great module. Any plans on updating to the latest testflight SDK? Or maybe structuring the module so that the testflight SDK plugs in to this module separately enabling easy SDK updates?

Thanks,
Michael

**Comment by dasmurphy** [comment]
Hi,

sure i will update it. Didn't had the time for an update. I think you have an update after christmas here. I hope this does not destroy any release time line.

I don't think it's possible to extract the .a and .h files from the module as separate, but you can take this source and try to compile the module yourself after updating the SDK.

Other information. I think i need to restructure anyway, because of the normal SDK and the new noadid version.

Hava a nice holyday. :)

**Comment by realsurfer** [comment]
Hi,
Thanks for your reply! Looking forward to an update.
I saw that this module https://marketplace.appcelerator.com/apps/4114?restoreSearch=true#!overview has separated out the SDK so it must be possible somehow.

Thanks!

**Comment by dasmurphy** [comment]
I will take a look in it, but i seems a more complicated setup than using my module with the included SDK.

The documentation at http://docs.clinsoftsolutions.com/testflightti/ states:

> unzip the zip archive
> Copy the libTestFlight.a to /usr/local/lib

This step is not needable with the baked in SDK ;)

**Comment by realsurfer** [comment]
I do agree that copying to /usr/local/lib is maybe not as clean. I guess both solutions have their pros and cons.

**Comment by Oshuma** [comment]
What's the status on the SDK update?  v2.0 has been deprecated and it's quite a few versions behind the latest release.
